tweets_df = read.csv("data/tweets_01-08-2021.csv")
approval_rating_df = read.csv("data/approval_topline.csv")
lawsuits_df = read.csv("data/trump_lawsuits.csv")
View(tweets_df)
View(approval_rating_df)
View(lawsuits_df)
